physics:
  model: 111  # Physics Contribution : - 100 = QED ; - 010 = Z ; 001 = Higgs ; 110 = QED + Z ; ... ; 111 = QED + Z + Higgs ;   
  sqrt_s: 1000  #[GeV] Center-of-mass energy
  m_e: 0.000511  #[GeV] Electron mass
  m_top: 172 #[GeV] Top quark mass          
  m_z: 91.188 #[GeV] Z boson mass
  m_h: 125  #[GeV] Higgs boson mass
  m_w: 80.419  #[GeV] W boson mass      
  gamma_z: 2.441404 #[GeV] Z boson decay width
  gamma_h: 0.006382339 #[GeV] Higgs boson decay width       
  renorm_scale: 365 #[GeV] Renormalization scale    
  alphaS: 0.1180 #alphaS(mZ) 
  alphaQED: 0.007546 #alphaQED(mZ)
  Nc: 3.0 #Number of colors
  m_mu: 0.10566 #[GeV] Muon mass
  m_tau: 1.7769 #[GeV] Tau mass
  m_u: 0.0022 #[GeV] Up quark mass
  m_d: 0.0047 #[GeV] Down quark mass
  m_c: 1.27 #[GeV] Charm quark mass
  m_s: 0.096 #[GeV] Strange quark mass
  m_b: 4.18 #[GeV] Bottom quark mass



generator:
  n_events: 10000 #Number of events to generate
  seed: 12 #Pseudo-random number generator seed
  weight_strategy: -4 #Do not modify
  nb_threads: 4 #Number of CPU cores used for computation
